id: IE02D92FE
legacy_id: P007070
ocr_import_info:
  bdrc_scan_id: W1KG11938
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T18:52:50'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:11:45.260017+00:00'
last_modified: 2022-08-31 11:11:52.086368
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG11938
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG11938
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྒྲོལ་མའི་ཆོས་སྐོར།
  author: འབྲི་གུང་པ་དཀོན་མཆོག་ནོར་བཟང་།
statistics:
  ocr_word_mean_confidence_index: 0.7810728337136525
  ocr_word_median_confidence_index: 0.8600000143051147
quality: null
bases:
  I1KG11941:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG11941
      total_pages: 190
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG11941.txt
    statistics:
      ocr_word_median_confidence_index: 0.8600000143051147
      ocr_word_mean_confidence_index: 0.7810728337136525
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
