id: IE02D92FE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T18:53:59+00:00'
last_modified: '2022-06-09T04:32:51.955034+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG11938
  title: སྒྲོལ་མའི་ཆོས་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E6A6:
      image_group_id: I1KG11941
      title: Volume 1 of sgrol ma'i chos skor/
      total_pages: 190
      order: 1
      base_file: E6A6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
