id: P007070
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 12:39:37.675066
source_metadata:
  id: bdr:W1KG11938
  title: སྒྲོལ་མའི་ཆོས་སྐོར།
  author: ''
  volumes:
    edf45545550e4bf59b59850ece40dc2f:
      image_group_id: I1KG11941
      title: Volume 1 of sgrol ma'i chos skor/
      volume_number: 1
      total_pages: 190
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
