id: P007070
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG11938
  title: སྒྲོལ་མའི་ཆོས་སྐོར།
  author: ''
  volumes:
    672d7c54179c47558b7f9db3e29dd152:
      image_group_id: I1KG11941
      title: ''
      volume_number: 1
      total_pages: 190
ebook_metadata:
  title: སྒྲོལ་མའི་ཆོས་སྐོར།
  author: ''
  sku: P007070
  cover: cover.jpg
  layers:
  - pagination
